### ISSUE TITLE
Verification of input from GUI

### ISSUE THREAD

**Issue by kael558** [wall-daniel/Risk#54]
for example, the user is currently able to select two countries of the same owner to attack

**Comment by wall-daniel** [comment]
Troop movement phase as well

**Comment by wall-daniel** [comment]
Maybe put in actionbuilder?

**Comment by wall-daniel** [comment]
Way easier than I originally planned.
I just checked if the country clicked was clickable, all the logic has already been done.

**Comment by wall-daniel** [comment]
Way easier than I originally planned.
I just checked if the country clicked was clickable, all the logic has already been done.
